import { describe, expect, test } from "bun:test";
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  ExitCode,
  type CliEnvelope,
  type ResearchRenderData,
} from "../../src/core/contracts/index.ts";
import { MOODBOARD_CSP } from "../../src/research/render/moodboard.ts";
import { runCliCaptured } from "../helpers/cli.ts";
import { e2eSetup } from "../helpers/e2e.ts";
import { hashTree } from "../helpers/fixtures.ts";
import { referenceArgs } from "../helpers/research.ts";

const { initialized } = e2eSetup();
const HOSTILE = '<script>alert("x")</script>';
const OUTPUTS = [
  "research/references.json",
  "research/provenance.json",
  "research/REFERENCES.md",
  "research/moodboards/index.html",
];

describe("heron research render", () => {
  // Covers: R13, R16
  test("renders reference-only outputs with escaped text and CSP", async () => {
    const root = await initialized("no-ux");
    const added = await runCliCaptured([...referenceArgs(root, ["origin"]), "--origin", HOSTILE]);
    expect(added.code).toBe(ExitCode.Ok);
    // Corrupt the derived views so the render has something to write.
    for (const view of ["REFERENCES.md", "moodboards/index.html"]) {
      writeFileSync(join(root, ".heron", "research", view), "stale");
    }
    const run = await runCliCaptured(["research", "render", root]);
    expect(run.code).toBe(ExitCode.Ok);
    expect(run.stderr).toBe("");
    expect(run.stdout).toContain("LOCALE_FALLBACK");
    expect(run.stdout).toContain(
      [
        "Research outputs (reference-only, locale en):",
        "- research/references.json: unchanged",
        "- research/provenance.json: unchanged",
        "- research/REFERENCES.md: written",
        "- research/moodboards/index.html: written",
        "References: 1 active, 0 removed; brand inputs: 0",
        "Open in a browser: .heron/research/moodboards/index.html",
        "State revision: 3",
      ].join("\n"),
    );
    const html = readFileSync(join(root, ".heron", "research", "moodboards", "index.html"), "utf8");
    const markdown = readFileSync(join(root, ".heron", "research", "REFERENCES.md"), "utf8");
    expect(html).toContain(
      `<meta http-equiv="Content-Security-Policy" content="${MOODBOARD_CSP}">`,
    );
    expect(html).not.toContain("<script>alert");
    expect(html).toContain("&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;");
    expect(markdown).toContain("\\<script\\>alert");
    expect(markdown).toContain("reference-only");
  });

  // Covers: R16
  test("renders byte-identical outputs and skips the write when nothing changed", async () => {
    const root = await initialized("no-ux");
    expect((await runCliCaptured(referenceArgs(root))).code).toBe(ExitCode.Ok);
    const first = await runCliCaptured(["research", "render", root, "--json"]);
    const before = hashTree(root, { exclude: [] });
    const second = await runCliCaptured(["research", "render", root, "--json"]);
    expect(first.code).toBe(ExitCode.Ok);
    expect(second.code).toBe(ExitCode.Ok);
    expect(hashTree(root, { exclude: [] })).toEqual(before);
    const data = (JSON.parse(second.stdout) as CliEnvelope).data as ResearchRenderData;
    expect(data.outputs.map((output) => [output.path, output.written])).toEqual(
      OUTPUTS.map((path) => [path, false]),
    );
    expect(data.stateRevision).toBe(2);
    expect((JSON.parse(first.stdout) as CliEnvelope).command).toBe("research render");

    // A hand edit of a derived view is regenerated byte for byte.
    const markdown = join(root, ".heron", "research", "REFERENCES.md");
    const original = readFileSync(markdown, "utf8");
    writeFileSync(markdown, `${original}\nhand edit`);
    const repaired = await runCliCaptured(["research", "render", root]);
    expect(repaired.code).toBe(ExitCode.Ok);
    expect(repaired.stdout).toContain("- research/REFERENCES.md: written");
    expect(readFileSync(markdown, "utf8")).toBe(original);
    expect(repaired.stdout).toContain("State revision: 3");
  });

  // Covers: R16
  test("renders agent documents into REFERENCES.md and leaves the other views alone", async () => {
    const root = await initialized("no-ux");
    expect((await runCliCaptured(referenceArgs(root))).code).toBe(ExitCode.Ok);
    const dir = join(root, ".heron", "research");
    const moodboard = readFileSync(join(dir, "moodboards", "index.html"), "utf8");
    // Fixed asset: the hostile payload lives in data, not in test source.
    copyFileSync(
      join(import.meta.dir, "..", "assets", "research", "hostile-brief.json"),
      join(dir, "brief.json"),
    );
    const rendered = await runCliCaptured(["research", "render", root]);
    expect(rendered.code).toBe(ExitCode.Ok);
    expect(rendered.stdout).toContain("- research/REFERENCES.md: written");
    expect(rendered.stdout).toContain("- research/moodboards/index.html: unchanged");
    const markdown = readFileSync(join(dir, "REFERENCES.md"), "utf8");
    expect(markdown).toContain("## Research brief");
    expect(markdown).toContain("\\<script\\>alert");
    expect(markdown).not.toContain("<script>");
    expect(readFileSync(join(dir, "moodboards", "index.html"), "utf8")).toBe(moodboard);
    const again = await runCliCaptured(["research", "render", root]);
    expect(again.stdout).toContain("- research/REFERENCES.md: unchanged");
  });

  // Covers: R13
  test("renders the es catalog without LOCALE_FALLBACK after init --locale es-MX", async () => {
    const root = await initialized("no-ux");
    expect((await runCliCaptured(["init", root, "--locale", "es-MX"])).code).toBe(ExitCode.Ok);
    expect((await runCliCaptured(referenceArgs(root))).code).toBe(ExitCode.Ok);
    const run = await runCliCaptured(["research", "render", root]);
    expect(run.code).toBe(ExitCode.Ok);
    expect(run.stdout).toContain("(reference-only, locale es):");
    expect(run.stdout).not.toContain("LOCALE_FALLBACK");
    const markdown = readFileSync(join(root, ".heron", "research", "REFERENCES.md"), "utf8");
    expect(markdown).toContain("Qué se estudia");
    const unknown = await runCliCaptured(["init", root, "--locale", "xx-YY"]);
    expect(unknown.code).toBe(ExitCode.Ok);
    const fallback = await runCliCaptured(["research", "render", root]);
    expect(fallback.stdout).toContain(
      'LOCALE_FALLBACK: No research copy for locale "xx-YY"; artifacts are rendered in en.',
    );
  });

  test("rejects unknown subcommands and extra arguments", async () => {
    const root = await initialized("no-ux");
    const unknown = await runCliCaptured(["research", "show", root]);
    expect(unknown.code).toBe(ExitCode.Usage);
    expect(unknown.stderr).toContain('Unknown research command "show". Expected: render.');
    const extra = await runCliCaptured(["research", "render", root, "extra"]);
    expect(extra.code).toBe(ExitCode.Usage);
  });
});
