# navori:managed start id="jscpd-script-check-jscpd" hash="65eb3b17" version="0.11.0" source="@navori/plugin-jscpd"
#!/usr/bin/env bash
# Generated by @navori/plugin-jscpd. Runs jscpd over TS/TSX files changed vs
# the configured base branch. Skips silently if jscpd or git are absent — the
# tool is optional, not a hard dependency of the project.
#
# Triggered as a PreToolUse(Bash) hook, gated to git commit — so the
# duplication check runs right before code lands, not on every turn.

set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# The sed fallback reads a JSON string through its first unescaped quote. JSON
# object member order is not a host contract: `command` can precede `cwd`, so a
# greedy capture to the last quote would swallow the rest of the payload when
# neither jq nor node is available.
# `${payload-$(cat)}` (unset test, not `:-`) rather than an unconditional
# `payload=$(cat)`: a caller that already captured stdin itself (spec 0035 —
# `managed-drift-watch.sh` needs the audit recorder's session_id/cwd even on
# tool names this hook does not otherwise read) keeps that value, empty or
# not, instead of this partial re-reading an already-drained pipe and
# clobbering it with "".
payload=${payload-$(cat)}
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -nE "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"(([^\"\\]|\\.)*)\".*/\\1/p"
}
extract_cmd() {
  payload_field tool_input.command
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.
cmd=$(extract_cmd)

navori_audit_name="check-jscpd"
navori_audit_phase="PreToolUse"
navori_audit_tool="Bash"
# `source` names the PLUGIN, not core: disabling a plugin changes which hooks
# run, and without this the report cannot explain why a phase thinned out
# between two sessions.
navori_audit_source="plugin:jscpd"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/render/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock — but only after establishing that anything will be recorded.
#
# THE COST OF BEING OFF is the number that matters here: this code is inlined
# into hooks that fire on EVERY Bash call, and audit-mode is off for virtually
# every session of every user. An earlier version ran `perl` plus two `jq`
# invocations before it ever checked whether a log existed — three processes per
# hook, four hooks per command, ~48 ms on every single shell call for a feature
# nobody had turned on.
#
# So the gate is a pure-builtin one first: the per-repo audit directory only
# exists once audit-mode has been activated in this repo at least once. No
# subprocess, no parsing. Everything expensive lives behind it.
navori_audit_begin() {
  navori_audit_on=0

  navori_audit_root=${NAVORI_AUDITS_ROOT:-}
  if [ -z "$navori_audit_root" ]; then
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi

  # The gate tests the audit ROOT, not the per-repo directory.
  #
  # Deriving the repo cheaply would mean `${CLAUDE_PROJECT_DIR##*/}` — and that
  # is WRONG: the authoritative repo comes from the payload's `cwd`, and the two
  # differ whenever a hook fires inside an agent worktree, since the hook process
  # starts in the main repo (#454). A gate built on the wrong name would silently
  # record nothing exactly where the harness runs its parallel work.
  #
  # The root alone is enough for what this gate is for: a user who has never
  # activated audit-mode anywhere has no `~/.navori/audits`, so the common case
  # costs one stat and zero processes. Someone who does use audit-mode pays the
  # parsing — which is the cost of the feature they turned on.
  [ -d "$navori_audit_root" ] || return 0

  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

# Milliseconds since epoch, spending a process only when it has to.
#
# `$EPOCHREALTIME` is a BUILTIN in bash 5 and in zsh (with zsh/datetime, which
# the harness's zsh path already has): no fork at all. Only a shell without it
# pays for `perl`, and only a machine without perl degrades to whole seconds —
# `date` has no portable millisecond format (GNU has %s%3N, BSD does not).
navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # The builtin-only gate from `navori_audit_begin`: when audit-mode was never
  # activated in this repo, nothing below runs and no process is spawned.
  [ "${navori_audit_on:-0}" = "1" ] || return 0
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  # ONE jq for every field, not one per field: this runs on each hook of each
  # Bash call, and a fork is the most expensive thing in it. Newline-separated,
  # read back positionally.
  # The third field is the OWNER, and it is never empty: inside a subagent the
  # host sends a real `agent_id`; on the main thread it sends none and the
  # literal below names the orchestrator explicitly.
  #
  # It used to be `// ""`, and the empty case did not stay empty — it came out
  # as the `cwd`. Command substitution strips trailing newlines, so an empty
  # third field left `$navori_audit_fields` with only two lines; then
  # `${rest#*<NL>}` found no newline in `"cwd"` and POSIX says a `#` pattern
  # that does not match returns the string UNCHANGED. 41,581 of the park's
  # 52,460 recorded owners (79%) were a filesystem path for that reason.
  #
  # The consumer's behaviour does not change — `ownerOf` looks the value up
  # among the session's agents and sends anything that names nobody to the
  # orchestrator, which is where a path already went — but the record stops
  # claiming the repo directory is an agent. Old logs keep working through the
  # same "names nobody" branch.
  #
  # The trailing "." is a sentinel, not data: with it the third field is always
  # followed by a newline, so the `%%` below cannot fall into the same trap if
  # a future field is ever empty.
  #
  # The owner is picked with an explicit "first non-empty string", NOT with
  # `.agent_id // .subagent_id // "orchestrator"`. In jq only `null` and `false`
  # are falsy, so a host that sends the key with an EMPTY string satisfies `//`
  # and the chain yields `""` — the field then disappears from the record and
  # `ownerOf` falls back to the time window, which is the guess this field
  # exists to avoid. Caught by a test, not by review.
  navori_audit_fields=$(printf '%s' "${payload:-}" | jq -r '[.session_id // "", .cwd // "", ([.agent_id, .subagent_id] | map(select(type == "string" and . != "")) | first) // "orchestrator", .tool_use_id // "", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_tool_use_id=${navori_audit_rest%%
*}
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  [ -n "$navori_audit_repo" ] || return 0

  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # The session may not be the marked one even in a repo that has been audited
  # before. Also the writability check — a log that cannot be appended to is not
  # an error, it is simply not recording.
  if [ ! -f "$navori_audit_file" ]; then
    # SPOOL for the phase that CANNOT have a log yet (#778).
    #
    # `navori audit --start` is what creates the session log, and it runs from
    # the UserPromptSubmit hook — i.e. after the first prompt. Every SessionStart
    # hook therefore fires BEFORE the file exists, and the check above threw its
    # record away every single time: measured, `session-start-context` recorded 1
    # of ~20 startups in this repo, and the only survivor was a resume onto an
    # already-open log. "Did the session load the harness?" had no witness at all,
    # which is exactly the question the recorder exists to answer.
    #
    # So those records go to a side file that `--start` absorbs. Two deliberate
    # limits keep this from becoming a leak:
    #
    #   1. SessionStart ONLY. Every other phase runs after a prompt, so a missing
    #      log there means the session is genuinely not marked — and spooling
    #      those would write four lines per Bash call, for every session of every
    #      repo, forever. That is thousands of writes to buy nothing.
    #   2. Only where the repo's audit directory ALREADY exists, which means the
    #      repo has been audited (or armed) at least once. `mkdir` is never run
    #      from here: a repo that has never used audit-mode must stay at zero
    #      files and zero forks, the same contract as the root gate above. The
    #      cost is that the FIRST audited session of a repo still loses its
    #      SessionStart records; every one after it has them.
    #
    # FAIL-OPEN, and here more than anywhere: this runs while a session is
    # opening. Every failure path below returns 0 and writes nothing to stdout —
    # a spool that could abort a hook would make observation the reason a session
    # does not start, which is the one bug this partial may never have.
    [ "${navori_audit_phase:-}" = "SessionStart" ] || return 0
    [ -d "$navori_audit_root/$navori_audit_repo" ] || return 0
    navori_audit_file=$navori_audit_root/$navori_audit_repo/pending-$navori_audit_session.jsonl
    if [ ! -e "$navori_audit_file" ]; then
      : >> "$navori_audit_file" 2>/dev/null || return 0
    fi
  fi
  [ -w "$navori_audit_file" ] || return 0

  # Volume valve, OFF by default.
  #
  # `PreToolUse(Bash)` chains four hooks, so every shell command leaves four
  # lines and most are `skip` — a long session runs to thousands. Set
  # NAVORI_AUDIT_SKIP_NOOPS=1 to drop the ones that did nothing.
  #
  # Default off on purpose: a `skip` is the ONLY evidence that a hook ran and
  # decided it had no business acting, which is exactly what distinguishes it
  # from a hook that never executed — the question that motivated recording
  # hooks at all. The valve trades that away knowingly; it must not be the
  # silent default.
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = "1" ]; then
    case "$1" in
      skip|noop) return 0 ;;
    esac
  fi

  navori_audit_end=$(navori_audit_now)
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  # `tsMs` is the instant at the resolution the log actually needs (#685): the
  # `ts` below truncates to the second, and 84% of a measured session's events
  # share their second with another one. This value is already computed — the
  # duration above is derived from it — so recording it costs nothing.
  #
  # Validated with the same `-ge 0` idiom as `ms`, and for the same reason: it
  # is passed as `--argjson`, so a non-numeric value would make the whole `jq`
  # fail and the event would vanish instead of merely losing a field.
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0

  # `ts` is NOT stamped here, and that is the whole point of #696: it was a
  # `date` fork per event — 46,850 of them across this store — for a string
  # fully derivable from the `tsMs` above, which `$EPOCHREALTIME` already
  # produced without spawning anything. The file's own cost doctrine (see
  # `navori_audit_now`) says spend a process only when there is no other way;
  # keeping this one made the comment lie four lines under the value that
  # refutes it.
  #
  # Nothing downstream lost a field: `parse.ts` derives the ISO from `tsMs`
  # when the record carries none, and logs written before this still have
  # theirs. The lifecycle records — `start`, `stop`, `session-end` — keep a real
  # `ts`, so a human reading the raw `.log` still has dated anchors; those are
  # ~3 per session, not one per hook.
  # `navori_audit_agent` came out of the same single jq above. It is what lets
  # the report attribute a hook to a subagent WITHOUT guessing: with agents
  # running in parallel their time windows overlap, so attribution by timestamp
  # is the fallback, not the primary route.
  #
  # It is recorded, never trusted as an agent identity by itself (#560). What
  # `.agent_id` means depends on the PHASE: on the tool phases it is stable —
  # 485 events of one measured session carried 11 distinct ids, and the
  # subagents' resolved to real transcripts — but on `SubagentStop` the host
  # sends a fresh id per firing: 112 distinct ids for 117 firings, 102 of them
  # matching nothing under `~/.claude`. So a consumer that resolves this field
  # must treat "names nobody" as invalid data rather than as a different agent
  # (`ownerOf` in `lib/audit/parse.ts` is where that rule lives).

  printf '%s\n' "$(jq -cn \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --arg toolUseId "${navori_audit_tool_use_id:-}" \
    --argjson ms "$navori_audit_ms" \
    --argjson tsMs "$navori_audit_end" \
    '{tsMs:$tsMs,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)
     + (if $toolUseId == "" then {} else {toolUseId:$toolUseId} end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin

# Same shape as quality-gate-pre-commit: fires on every Bash call, works on
# almost none, so the verdict comes from the exit code rather than from a call
# per branch.
navori_audit_on_exit() {
  navori_audit_code=${1:-$?}
  # A cancelled hook reaches this trap with `$?` == 0 (#797), so the exit code
  # below cannot tell "finished green" from "was killed mid-scan". The signal
  # handler can, and it already recorded the run.
  if [ -n "${navori_audit_signal:-}" ]; then
    return 0
  fi
  if [ "$navori_audit_code" -eq 0 ]; then
    navori_audit_log "allow" "${navori_jscpd_reason:-jscpd: no scan result recorded}" || true
  elif [ "$navori_audit_code" -eq 2 ]; then
    navori_audit_log "block" "${navori_jscpd_reason:-jscpd: blocking outcome, not a confirmed duplication verdict}" || true
  else
    navori_audit_log "allow" "${navori_jscpd_reason:-jscpd: scan not validated (hook error)}" || true
  fi
  return 0
}
trap navori_audit_on_exit EXIT
# Signal traps (TERM/INT/HUP) + `navori_audit_signal`. Shared body, single
# source of truth: the three gates are killed the same way and must record it
# the same way.
# Shared "the host cancelled this hook" recorder — inlined into the three gate
# hooks at render time (see the include directive in the source scripts +
# lib/render/hook-includes.ts).
#
# WHY (#797): a `command` hook that reaches its host timeout is CANCELLED, and
# bash still runs the EXIT trap on the way out with `$?` == 0 — the last
# COMPLETED command was the `trap` builtin itself. So the recorder's "exit code
# is zero" branch recorded a gate aborted after 3 seconds of a 20-second run as
# `allow`, "gate ejecutado y verde". Reproduced end to end on the RENDERED hook;
# the only trace of the truth was an `ms` nobody reads.
#
# That false green is worse than the absence it replaced: `quality-gate-aborted`
# only fires on a `gate-started` with NO terminal record, so the fake `allow`
# satisfied the detector and disarmed it. The signal itself is therefore the
# witness — recorded here, before the process dies, under its own verdict
# (`gate-killed`): never `allow`, never `block`. Nothing was validated, and the
# host had already discarded this hook's output when it sent the signal.
#
# The docs do not say WHICH signal the host uses to cancel, so this covers the
# handled ones (TERM/INT/HUP) while `gate-started` keeps covering SIGKILL, which
# no handler can ever observe. Both halves are needed: either one alone detects
# a scenario that may not be the one that happens.
#
# FAIL-OPEN like everything else in the recorder: the handler records, re-raises
# the ORIGINAL signal with its default disposition — so the process still dies
# from what it was sent instead of continuing as if nothing happened — and never
# changes what the host does with the tool call. It is deliberately NOT a
# process-tree kill: the gate's own child (`pnpm lint`, `semgrep`, `jscpd`)
# already outlives the hook today, and killing someone else's build from an
# observer is a decision of its own (#797, residue 3).
#
# SIGNAL DEFERRAL, so the recorded `ms` is not read as a second lie: bash does
# not run a trap while it waits for a foreground command, so under bash the
# record lands when the gate command FINISHES, not when the signal arrived. The
# verdict is the same either way and the host is long gone by then; only the
# instant differs.
#
# `navori_audit_signal` is what keeps the two recorders from both writing: the
# EXIT trap runs after this one and must stay quiet, since its `$?` is exactly
# the value that cannot be trusted here.
navori_audit_signal=""
navori_audit_on_signal() {
  navori_audit_signal=$1
  navori_audit_log "gate-killed" "cancelado por SIG$1: nada quedo validado" || true
  # `|| true` on both: a recorder may never become the reason a hook fails, and
  # `set -e` is on in every script that includes this.
  trap - "$1" 2>/dev/null || true
  kill -s "$1" "$$" 2>/dev/null || true
  return 0
}
trap 'navori_audit_on_signal TERM' TERM
trap 'navori_audit_on_signal INT' INT
trap 'navori_audit_on_signal HUP' HUP

# Gate to `git commit` only (this copy runs on commit, not push). $TRIGGER_RE is
# consumed by the shared detector inlined below.
TRIGGER_RE='^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+commit([[:space:]]|$)'
# Literal substrings every branch of $TRIGGER_RE needs; read by the fast
# path in the shared detector below (spec 0016). Keep NEXT to the regex:
# a branch added there without its token here silently loses the shortcut
# (fail-open to the slow path), and the inlined tests pin the pairing.
TRIGGER_TOKENS='commit'
# Heredoc bodies fed to `cat` are data, not commands (#1095).
TRIGGER_STRIP_HEREDOC_BODIES=1
# Shared gate detector — inlined into each hook at render time (see the include
# directive in the source scripts + lib/render/hook-includes.ts). The caller MUST set
# $TRIGGER_RE (an ERE) before the include; it decides which git ops this hook
# gates. Single source of truth for the FIX B/C wrapper-peeling logic; DO NOT
# copy this body into a hook by hand.
#
# Detect whether $1 (a possibly-compound command) invokes a gated operation.
# Splits $1 on the shell separators && || ; | and newlines, strips leading
# whitespace plus wrapper words (`(`, `\`, `command `) and `VAR=value` env
# prefixes from each segment, and returns 0 if ANY segment STARTS with a gated
# `git …` invocation on a word boundary (matched by $TRIGGER_RE). Replaces
# literal-prefix `case` matching, which silently skipped the gate for
# `cd x && git commit`, `echo y; git push`, or a leading space (#88: NEVER skip
# the gate silently). Matching a segment START means a quoted `echo "git commit"`
# does NOT trigger it. Known limitation: it cannot see through `sh -c`, `eval`,
# or obfuscation — a seatbelt, not a sandbox.
#
# Heredoc bodies (#1095): when the caller sets TRIGGER_STRIP_HEREDOC_BODIES=1,
# the body of a `cat <<TAG … TAG` heredoc is DATA, not commands, so a
# `git commit` line inside e.g. a `gh issue create --body "$(cat <<'EOF' …`
# no longer counts. It is an ALLOW-list on purpose: only a `cat` heredoc (bare,
# or inside `$(…)` of gh/git/echo/printf) with nothing chained after it is
# stripped; anything else — `bash <<EOF`, `while read c; do $c; done <<EOF`,
# `cat <<EOF | sh`, `python - <<EOF` — keeps its body, because a shell or
# interpreter may execute it. Opt-in because master-accept-confirm matches
# unanchored and must keep seeing bodies fed to a non-shell interpreter.
# The fast path on its own, so a caller can apply it EARLIER than the segment
# scan — before it has even paid to extract the command from the payload.
#
# Returns 0 when $1 may contain a gated operation, 1 when it provably cannot.
# The argument is the one the block below spells out: no $TRIGGER_RE can match
# without one of the caller's literal TOKENS appearing in the segment it
# matches, and every segment is a substring of the input. So the absence of
# every token is proof that no segment can match — and the same proof holds one
# level up, over the raw PAYLOAD the command was extracted from: JSON escaping
# touches `"`, `\` and control characters, never the letters of a token.
#
# Disarms when $TRIGGER_TOKENS is unset: with no tokens declared there is
# nothing to prove absent, so it answers "maybe" and the caller does the work.
# Fail-open to the SLOW path, never to a skip.
has_trigger_token() {
  [ -n "${TRIGGER_TOKENS:-}" ] || return 0
  # Token iteration goes through newline-split + `read`, NOT `for _tok in
  # $TRIGGER_TOKENS`: zsh does not word-split an unquoted expansion, so the
  # `for` form iterated ONCE with the whole list as a single token there — and
  # a token that can never match is a gate that never fires. Caught by the
  # bash×zsh differential suite.
  local _input="$1" _tok _nl=$'\n'
  local _toks="${TRIGGER_TOKENS// /$_nl}"
  while IFS= read -r _tok; do
    [ -n "$_tok" ] || continue
    case "$_input" in *"$_tok"*) return 0 ;; esac
  done <<< "$_toks"
  return 1
}

# Words that let a later part of a command re-enter git, the cwd or a shell.
# Text is reduced to alphanumeric words first, so `/usr/bin/git` and `(cd` match.
navori_mentions_shellish() {
  local t=" ${1//[!A-Za-z0-9_]/ } "
  case "$t" in
    *" git "*|*" cd "*|*" pushd "*|*" popd "*|*" sh "*|*" bash "*|*" zsh "*|*" dash "*|*" ksh "*) return 0 ;;
    *" env "*|*" eval "*|*" exec "*|*" command "*|*" builtin "*|*" source "*|*" xargs "*) return 0 ;;
  esac
  return 1
}

# Sets `navori_heredoc_stripped` to $1 minus the bodies (and terminators) of
# heredocs this hook may safely treat as data; the introducing line is KEPT, so
# `git commit -F - <<'EOF'` still triggers. Any doubt (second heredoc on the
# line, unterminated body, empty tag) leaves the text untouched: fail closed.
# All locals are declared once at the top: zsh prints a re-declared `local`.
navori_strip_heredoc_bodies() {
  local input="$1" line before rest seg pre pfirst tag after cmp="" out="" r=""
  local dash=0 inbody=0 tab=$'\t' nl=$'\n'
  navori_heredoc_stripped="$input"
  case "$input" in *'<<'*) ;; *) return 0 ;; esac
  while IFS= read -r line; do
    if [ "$inbody" = 1 ]; then
      cmp="$line"
      if [ "$dash" = 1 ]; then cmp="${cmp#"${cmp%%[!$tab]*}"}"; fi
      if [ "$cmp" = "$tag" ]; then inbody=0; fi
      continue
    fi
    out="$out$line$nl"
    case "$line" in *'<<'*) ;; *) continue ;; esac
    before="${line%%<<*}"
    rest="${line#*<<}"
    case "$rest" in '<'*) continue ;; esac                  # here-string: no body
    dash=0
    case "$rest" in -*) dash=1; rest="${rest#-}" ;; esac
    rest="${rest#"${rest%%[![:space:]]*}"}"
    tag=""; after=""
    case "$rest" in
      \'*) r="${rest#\'}"; case "$r" in *\'*) tag="${r%%\'*}"; after="${r#*\'}" ;; esac ;;
      \"*) r="${rest#\"}"; case "$r" in *\"*) tag="${r%%\"*}"; after="${r#*\"}" ;; esac ;;
      \\*) r="${rest#\\}"; tag="${r%%[!A-Za-z0-9_.-]*}"; after="${r#"$tag"}" ;;
      *) tag="${rest%%[!A-Za-z0-9_.-]*}"; after="${rest#"$tag"}" ;;
    esac
    [ -n "$tag" ] || continue
    # Nothing chained after the tag, and no second heredoc on the line.
    case "$after" in *'|'*|*';'*|*'&'*|*'<<'*) continue ;; esac
    # The word before `<<` must be `cat`. Inside `$(…)`/backticks the command
    # that receives cat's output must be a known data consumer, not an
    # interpreter (`bash -c "$(cat <<EOF`, `eval "$(cat <<EOF`).
    seg="$before"
    case "$before" in
      *'$('*) seg="${before##*\$\(}"; pre="${before%\$\(*}" ;;
      *'`'*) seg="${before##*\`}"; pre="${before%\`*}" ;;
      *) pre="" ;;
    esac
    if [ -n "$pre" ]; then
      pre="${pre##*&&}"; pre="${pre##*;}"; pre="${pre##*|}"
      pre="${pre#"${pre%%[![:space:]]*}"}"
      pfirst="${pre%%[[:space:]]*}"
      case "$pfirst" in gh|git|echo|printf) ;; *) continue ;; esac
    fi
    seg="${seg#"${seg%%[![:space:]]*}"}"
    case "$seg" in *'|'*|*';'*|*'&'*) continue ;; esac
    case "$seg" in cat|cat[[:space:]]*) ;; *) continue ;; esac
    inbody=1
  done <<< "$input"
  [ "$inbody" = 0 ] || return 0                             # unterminated: keep all
  navori_heredoc_stripped="$out"
  return 0
}

# Counts the segments of $1 that start with a gated op ($TRIGGER_RE); sets the
# global `navori_trigger_hits`. `$2` = 1 stops at the first hit (is_scan_trigger
# only needs "any"). The single home of the segment normalisation, shared with
# navori_commit_landing so the two can never disagree about what a segment is.
navori_count_triggers() {
  # Pre-expanded newline: zsh does NOT expand $'\n' in the REPLACEMENT of
  # ${var//pat/repl} (it inserts the literal characters), so an inline $'\n'
  # left compound commands unsplit there and the gate silently skipped
  # `cd x && git commit` (#391). A plain variable expands identically in
  # bash and zsh. ($'\n' in PATTERN position expands fine in both.)
  local input="$1" stop="${2:-0}" segment nl=$'\n'
  navori_trigger_hits=0
  if [ "${TRIGGER_STRIP_HEREDOC_BODIES:-}" = 1 ]; then
    case "$input" in *'<<'*) navori_strip_heredoc_bodies "$input"; input="$navori_heredoc_stripped" ;; esac
  fi
  # FIX B: join `\<newline>` continuations into a space FIRST, so a command
  # split across lines with a trailing backslash stays ONE logical segment
  # (otherwise the subcommand/flag lands in a segment not starting with git).
  input="${input//\\$'\n'/ }"
  input="${input//&&/$nl}"
  input="${input//||/$nl}"
  input="${input//;/$nl}"
  input="${input//|/$nl}"
  # `<<<` feeds the already-expanded value as data — no re-evaluation — so a
  # command that contains backticks/$() is inspected, never executed.
  while IFS= read -r segment; do
    segment="${segment#"${segment%%[![:space:]]*}"}"        # strip leading ws
    # FIX C: peel wrappers so `(git …`, `\git`, `command git …` and
    # `VAR=val git …` all reduce to a plain `git …` before matching.
    while [[ "$segment" == \(* ]]; do                       # strip leading ( runs
      segment="${segment#\(}"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    done
    segment="${segment#\\}"                                 # strip a leading backslash (\git)
    while [[ "$segment" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; do  # strip VAR=val prefixes
      case "$segment" in
        *[[:space:]]*)
          segment="${segment#*[[:space:]]}"
          segment="${segment#"${segment%%[![:space:]]*}"}"
          ;;
        *) segment=""; break ;;
      esac
    done
    if [[ "$segment" == command\ * ]]; then                 # strip a leading `command ` word
      segment="${segment#command }"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    fi
    # FIX C: allow git global options between `git` and the subcommand
    # (`git -c k=v commit`, `git -C /repo push`). $TRIGGER_RE's trailing boundary
    # keeps `git commitgraph` / `git config …` from matching.
    if printf '%s' "$segment" | grep -qE "$TRIGGER_RE"; then
      navori_trigger_hits=$((navori_trigger_hits + 1))
      if [ "$stop" = 1 ]; then return 0; fi
    fi
  done <<< "$input"
  return 0
}

is_scan_trigger() {
  # ─── Fast path (spec 0016 T3.2, second pass): the segment loop pays one
  # `grep -qE` FORK per segment — and a heredoc body or a 40-step compound
  # is 40 segments, so the field cost scaled with command length (measured:
  # 2.8 ms trivial, 14.8 ms for a 199-char heredoc, 95.8 ms for 40 segments;
  # p50 across one real session's commands was 40 ms per hook, not the
  # trivial floor). No $TRIGGER_RE can match without one of the caller's
  # literal TOKENS appearing in the segment it matches — and every segment is
  # a substring of the input, transformed only by insertions (`\<NL>` → space,
  # separators → newline) and prefix-peeling, none of which can CREATE a
  # token. So a single in-process substring scan of the raw input is a strict
  # superset of the segment matches: if no token is present, no segment can
  # match, and the gate answers "not for me" without a single fork. Same
  # argument, same safe direction, as the guard's own fast path.
  #
  # $TRIGGER_TOKENS is set by the including hook NEXT TO its $TRIGGER_RE, so
  # the pair travels together; when unset the fast path disarms and the loop
  # runs exactly as before (fail-open to the SLOW path, never to a skip).
  has_trigger_token "$1" || return 1
  navori_count_triggers "$1" 1
  [ "$navori_trigger_hits" -gt 0 ]
}

# Resolution of the working tree the commit acts on (#454). Shared body.
# Shared worktree resolver — inlined into each gate hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Requires the
# `extract-cmd` partial to have run first ($payload and $cmd in scope).
#
# WHY (#454): settings.json invokes these hooks as
# `bash "$CLAUDE_PROJECT_DIR/.claude/scripts/check-semgrep.sh"`, so the hook
# PROCESS starts in the MAIN repo even when the commit happens inside an agent
# worktree under `.claude/worktrees/`. The old `cd "$(git rev-parse
# --show-toplevel)"` therefore resolved the main repo — whose tree is clean — so
# `git diff --name-only main` returned 0 files and the gate exited 0. Not a false
# negative from the scanner: the scanner never ran. A `cd` to an arbitrary tree
# is exactly the bug, so nothing below ever guesses: every candidate must prove
# it is a git working tree, or the next one is tried — and the one the COMMAND
# names must additionally prove it is part of the repository being protected
# (see the same-repository constraint in `navori_worktree`).
#
# `navori_worktree` prints the absolute root of the working tree the gated git
# command will act on, or nothing when none resolves. It is a FUNCTION, not a
# top-level assignment, because `quality-gate-pre-commit` inlines this partial on
# a path that runs on EVERY Bash tool call: callers pay the git/jq probes only
# after their own trigger matched.

# First shell token of $1: a leading single/double-quoted string (so a path with
# spaces survives) or an unquoted run of non-space characters.
navori_first_token() {
  local s="$1"
  case "$s" in
    \"*) s="${s#\"}"; printf '%s' "${s%%\"*}" ;;
    \'*) s="${s#\'}"; printf '%s' "${s%%\'*}" ;;
    *) printf '%s' "${s%%[[:space:]]*}" ;;
  esac
}

# Directory named by the command itself, if any. Two shapes, both real in this
# harness: `git -C <dir> commit …` (git names its own tree) and
# `cd <dir> && git commit …` (how an agent commits into its worktree from a
# session anchored elsewhere). Prints the raw token; the caller resolves it.
#
# TODO(scope): only the FIRST segment is inspected for `cd`. A `cd` buried
# mid-chain (`pnpm build && cd sub && git commit`) falls through to the payload
# cwd, which is right whenever that `cd` stays inside the same repo. Walk the
# segments if a real command shows up where it does not.
navori_cmd_dir() {
  local text="$1" rest="" head=""
  case "$text" in
    *"git -C "*)
      rest="${text#*git -C }"
      ;;
    *)
      head="${text%%&&*}"
      head="${head#"${head%%[![:space:]]*}"}"
      case "$head" in
        "cd "*) rest="${head#cd }" ;;
      esac
      ;;
  esac
  [ -n "$rest" ] || return 1
  rest="${rest#"${rest%%[![:space:]]*}"}"
  # A token that needs the shell to expand it ($VAR, `sub`, ~, globs) is NOT
  # resolved here: guessing wrong points the scan at the wrong tree, which is
  # the very failure this partial exists to kill. Ignoring it just falls through
  # to the next candidate.
  case "$rest" in
    ""|*'$'*|*'`'*|*'*'*|*'?'*|"~"*) return 1 ;;
  esac
  navori_first_token "$rest"
}

# Absolute, symlink-resolved path of a working tree's SHARED git dir, or nothing
# when $1 is not inside a git working tree. `--git-common-dir` names the `.git`
# of the MAIN checkout, so every linked worktree of one repository — and every
# subdirectory of it — reports the SAME value, while a different repository
# reports its own and a submodule reports `<main>/.git/modules/<name>`. That
# makes it an identity test for "same repository", which `--show-toplevel` (one
# per working tree) and `--git-dir` (one per worktree) are not.
navori_repo_id() {
  local dir="$1" common=""
  common=$(git -C "$dir" rev-parse --git-common-dir 2>/dev/null) || return 1
  [ -n "$common" ] || return 1
  # `git -C <dir>` chdirs to <dir> first, so a relative answer (`.git`,
  # `../../.git`) is relative to <dir>. `pwd -P` canonicalises both sides the
  # same way, which also settles macOS's /var vs /private/var symlink.
  (cd "$dir" && cd "$common" && pwd -P) 2>/dev/null
}

# First argument that resolves to a git working tree; prints its root.
navori_first_tree() {
  local candidate toplevel
  for candidate in "$@"; do
    [ -n "$candidate" ] || continue
    [ -d "$candidate" ] || continue
    toplevel=$(git -C "$candidate" rev-parse --show-toplevel 2>/dev/null) || continue
    [ -n "$toplevel" ] || continue
    printf '%s' "$toplevel"
    return 0
  done
  return 1
}

# Resolution, most specific first:
#   1. the directory the command names (`git -C` / a leading `cd`), ONLY when it
#      belongs to the same repository as the anchor (see the constraint below);
#   2. the payload's `.cwd` — Claude Code sends the CURRENT working directory of
#      the tool call, a documented field distinct from $CLAUDE_PROJECT_DIR (the
#      project root). In an agent worktree these differ; that gap IS #454;
#   3. the hook process's own cwd — the pre-#454 behaviour, still correct for a
#      plain terminal or git-hook invocation.
navori_worktree() {
  local payload_cwd anchor named anchor_repo="" named_repo=""
  payload_cwd=$(payload_field cwd)
  # A relative `cd sub` resolves against the shell's cwd, which is the payload's
  # when Claude Code sends one and the hook process's otherwise.
  anchor="$payload_cwd"
  [ -d "$anchor" ] || anchor="$PWD"
  named=$(navori_cmd_dir "$cmd" || true)
  case "$named" in
    "") ;;
    /*) ;;
    *) named="$anchor/$named" ;;
  esac
  # SAME-REPOSITORY CONSTRAINT — DO NOT REMOVE (#454, review finding).
  # Candidate 1 is the only one the COMMAND controls, and it is tried first, so
  # accepting any git tree it happens to name lets that command OVERRIDE the
  # trustworthy candidates below it: `git -C <other-repo> log && git commit`,
  # `cd <other> && cd <wt> && git commit`, `cd <sub> && cd .. && git commit`, or
  # merely the bytes `git -C <path>` inside a commit MESSAGE, all aimed the scan
  # at a foreign tree with nothing to scan — exit 0 with the scanner never run,
  # which is the very failure #454 is about (and, for a commit in the main repo,
  # strictly worse than not resolving worktrees at all).
  # So a directory the command names is accepted only when it is part of the
  # repository the hook is protecting, i.e. the anchor's. Linked worktrees share
  # the main checkout's git dir, so every legitimate agent worktree passes; a
  # different repository and a submodule (its own git dir under
  # `<main>/.git/modules/`) do not, and fall through to the payload cwd — the
  # stricter direction. An unresolvable anchor drops candidate 1 for the same
  # reason: nothing to check it against.
  # Ceiling: two linked worktrees of the SAME repository are indistinguishable
  # this way, so naming a sibling worktree still beats the payload cwd. Both are
  # trees of the repo being protected, so the scan stays inside it. Walk the
  # segments to the one that actually carries the `git commit` if a real command
  # shows up where that is not enough.
  if [ -n "$named" ]; then
    anchor_repo=$(navori_repo_id "$anchor" || true)
    named_repo=$(navori_repo_id "$named" || true)
    if [ -z "$anchor_repo" ] || [ "$named_repo" != "$anchor_repo" ]; then
      named=""
    fi
  fi
  navori_first_tree "$named" "$payload_cwd" "$PWD" || true
}

# ─── Where does the commit LAND? (#1095) ────────────────────────────────────────
# `navori_worktree` above answers "which tree do I scan"; this answers "is the
# commit even for the repository this gate protects". A commit that provably
# lands in ANOTHER repository (`cd <other> && git commit`, `git -C <other>
# commit`) must not be gated against the anchor's tree: that tree holds none of
# the diff. Classification is a POSITIVE grammar with a deny-list of ambiguity —
# `foreign` only when every step to the commit has a certain cwd effect and the
# resolved repository really differs; the commit message is never read (#454:
# `git commit -m "use git -C <other>"` lands in the anchor). Anything unsure is
# `ambiguous`, which callers treat exactly like `same-repo`: run the gate.
#
# Requires the `gate-trigger` partial (navori_count_triggers, $TRIGGER_RE) and
# `extract-cmd` (payload_field). Always returns 0 and sets, without a subshell:
#   navori_landing       same-repo | foreign | ambiguous
#   navori_landing_root  landing toplevel (foreign only)
# "foreign" means different from BOTH the payload-cwd repository and the
# repository of $CLAUDE_PROJECT_DIR (the one the hook belongs to): a session
# anchored in repo B that commits into the hook's own repo must still be gated.
# Codex exposes no equivalent env var in these hooks (`nv_project_dir` is derived
# from the payload cwd, hook-input.sh), so there the comparison degrades to
# payload-cwd-only.
navori_commit_re='^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+commit([[:space:]]|$)'

# Reads one shell token off the front of $1 into `navori_tok` / `navori_rest`.
# Returns 1 for anything the shell would expand or that is malformed, so the
# caller falls back to `ambiguous`.
navori_take_token() {
  local s="$1" nl=$'\n'
  navori_tok=""; navori_rest=""
  s="${s#"${s%%[![:space:]]*}"}"
  case "$s" in
    \'*)
      s="${s#\'}"
      case "$s" in *\'*) ;; *) return 1 ;; esac
      navori_tok="${s%%\'*}"; navori_rest="${s#*\'}"
      case "$navori_rest" in ""|[[:space:]]*) ;; *) return 1 ;; esac
      ;;
    \"*)
      s="${s#\"}"
      case "$s" in *\"*) ;; *) return 1 ;; esac
      navori_tok="${s%%\"*}"; navori_rest="${s#*\"}"
      case "$navori_rest" in ""|[[:space:]]*) ;; *) return 1 ;; esac
      ;;
    *)
      navori_tok="${s%%[[:space:]]*}"; navori_rest="${s#"$navori_tok"}"
      case "$navori_tok" in
        *';'*|*'|'*|*'&'*|*'<'*|*'>'*|*'('*|*')'*|*"'"*|*'"'*) return 1 ;;
      esac
      ;;
  esac
  case "$navori_tok" in
    ""|'~'*|*'$'*|*'`'*|*'\'*|*'*'*|*'?'*|*'['*|*'{'*|*"$nl"*) return 1 ;;
  esac
  return 0
}

navori_commit_landing() {
  local c rest seg first tailtxt p arg dir base pcwd top sub id_l id_a id_h
  local cd_dir="" c_dir="" found=0 more=1 cdcount=0 nc=0 rel=0 nl=$'\n'
  navori_landing="ambiguous"; navori_landing_root=""

  # A single gated op only: a second commit (or, in semgrep, a push) makes the
  # landing repo of "the" commit undefined.
  navori_count_triggers "$1" 0
  [ "$navori_trigger_hits" = 1 ] || return 0

  navori_strip_heredoc_bodies "$1"
  c="$navori_heredoc_stripped"
  c="${c//\\$'\n'/ }"

  # Walk the `&&` chain up to the commit segment; every earlier segment must be a
  # single `cd <literal>` (at most one) or a neutral `git …` that cannot move the
  # shell's cwd or env.
  rest="$c"
  while [ "$more" = 1 ]; do
    case "$rest" in
      *'&&'*) seg="${rest%%&&*}"; rest="${rest#*&&}" ;;
      *) seg="$rest"; rest=""; more=0 ;;
    esac
    seg="${seg#"${seg%%[![:space:]]*}"}"
    first="${seg%%"$nl"*}"
    case "$first" in
      git[[:space:]]*)
        if printf '%s' "$first" | grep -qE "$navori_commit_re"; then found=1; break; fi
        ;;
    esac
    case "$seg" in *"$nl"*) return 0 ;; esac
    seg="${seg%"${seg##*[![:space:]]}"}"
    case "$seg" in
      cd[[:space:]]*)
        [ "$cdcount" = 0 ] || return 0
        cdcount=1
        navori_take_token "${seg#cd}" || return 0
        case "$navori_rest" in *[![:space:]]*) return 0 ;; esac
        cd_dir="$navori_tok"
        case "$cd_dir" in -*) return 0 ;; esac
        ;;
      git[[:space:]]*)
        case "$seg" in
          *';'*|*'|'*|*'&'*|*'<'*|*'>'*|*'('*|*')'*|*'$'*|*'`'*) return 0 ;;
        esac
        ;;
      *) return 0 ;;
    esac
  done
  [ "$found" = 1 ] || return 0

  # The commit segment's own global options, positionally. Text after `commit`
  # (the message) is never read.
  p="${first#git}"
  while :; do
    navori_take_token "$p" || return 0
    arg="$navori_tok"; p="$navori_rest"
    case "$arg" in
      commit) break ;;
      -C)
        [ "$nc" = 0 ] || return 0
        nc=1
        navori_take_token "$p" || return 0
        c_dir="$navori_tok"; p="$navori_rest"
        ;;
      -c) navori_take_token "$p" || return 0; p="$navori_rest" ;;
      --no-pager|-p|--paginate|-P|--no-optional-locks|--literal-pathspecs|--glob-pathspecs|--noglob-pathspecs|--icase-pathspecs|--no-replace-objects) ;;
      *) return 0 ;;
    esac
  done

  # Anything that runs AFTER the commit and could re-enter git, cd or a shell
  # (a second, uncounted commit landing elsewhere) makes the verdict unsafe.
  tailtxt="${seg#"$first"}$nl$rest"
  case "$first" in *';'*|*'|'*|*'&'*) tailtxt="${first#*[;|&]}$nl$tailtxt" ;; esac
  if navori_mentions_shellish "$tailtxt"; then return 0; fi

  if [ -z "$cd_dir" ] && [ -z "$c_dir" ]; then
    navori_landing="same-repo"; return 0
  fi

  pcwd=$(payload_field cwd)
  base="$pcwd"
  [ -d "$base" ] || base="$PWD"
  dir="$base"
  if [ -n "$cd_dir" ]; then
    case "$cd_dir" in
      /*) dir="$cd_dir" ;;
      *)
        rel=1; dir="$base/$cd_dir"
        # A non-empty CDPATH can make `cd <relative>` land somewhere else.
        [ -z "${CDPATH:-}" ] || return 0
        ;;
    esac
  fi
  if [ -n "$c_dir" ]; then
    case "$c_dir" in
      /*) dir="$c_dir"; rel=0 ;;
      *) rel=1; dir="$dir/$c_dir" ;;
    esac
  fi
  # `..` in a relative path resolves logically in the shell but physically in
  # the kernel; they differ when the base itself sits behind a symlink.
  if [ "$rel" = 1 ]; then
    case "$cd_dir$nl$c_dir" in
      *'..'*) [ "$(cd "$base" 2>/dev/null && pwd -P)" = "$base" ] || return 0 ;;
    esac
  fi

  [ -d "$dir" ] || return 0
  top=$(git -C "$dir" rev-parse --show-toplevel 2>/dev/null) || return 0
  [ -n "$top" ] || return 0
  # A submodule target is deliberately not `foreign` (its commit is part of the
  # superproject's work): the anchor's gate runs.
  sub=$(git -C "$dir" rev-parse --show-superproject-working-tree 2>/dev/null) || return 0
  [ -z "$sub" ] || return 0
  id_l=$(navori_repo_id "$dir" || true)
  id_a=$(navori_repo_id "$base" || true)
  [ -n "$id_l" ] && [ -n "$id_a" ] || return 0
  id_h=""
  if [ -n "${CLAUDE_PROJECT_DIR:-}" ]; then
    id_h=$(navori_repo_id "$CLAUDE_PROJECT_DIR" || true)
  fi
  if [ "$id_l" = "$id_a" ] || { [ -n "$id_h" ] && [ "$id_l" = "$id_h" ]; }; then
    navori_landing="same-repo"
  else
    navori_landing="foreign"; navori_landing_root="$top"
  fi
  return 0
}

# Baseline resolution + the list of files in scope (#777). Shared body with
# check-semgrep, so the two scanners can never disagree about what they compare
# against or about which files they read. `$navori_scan_label` names this hook
# in its messages.
#
# THE UNTRACKED DECISION (#777), written here because it is this hook's whole
# second chance: jscpd gates `git commit` and nothing else, while semgrep also
# gates `git push` and `gh pr create`. So a new file that slipped past semgrep
# at commit time is still caught on the push; one that slips past jscpd is
# never looked at again, and duplicated new code lands unseen. Two ways to fix
# it: include untracked files in the scan, or add a push trigger. This hook
# takes the FIRST — it closes the hole in the layer where it lives (the scan
# reads what the commit is about to contain), it is symmetric with semgrep so
# one shared partial serves both, and it does not make a duplication check fire
# on an operation that adds no code. Revisit only if commits start landing
# content that is neither tracked nor untracked at hook time.
navori_scan_label="jscpd"
# Shared scan scope — inlined into the diff-scanning gate hooks at render time
# (see the include directive in the source scripts + lib/render/hook-includes.ts).
# DO NOT copy this body back into a hook by hand: hand-synced copies are how the
# two scanners drifted apart in the first place (#225/#261, and #777 below).
#
# Single source of truth for the two questions every diff scanner answers before
# it runs: WHAT is the baseline, and WHICH files are in scope. `check-semgrep`
# and `check-jscpd` used to answer both with copies that had already diverged —
# jscpd never resolved its base to a sha, so its cache and its scan could name
# different commits.
#
# Requires, from the caller: `$base` (the configured base branch, shell-quoted
# at render time via the `shq:` marker) and a cwd already inside the working
# tree being scanned. `$navori_scan_label` names the caller in every message.

# --- Baseline (#777) ---------------------------------------------------------
# `origin/<base>` FIRST, the local ref only as a fallback.
#
# The local ref carries NO freshness guarantee. An agent worktree is cut from
# whatever `main` pointed at that moment and never moves again, and a main
# checkout nobody pulls is the same shape. A baseline taken from it drifts
# behind every change that lands meanwhile, and the scan then compares against
# a tree that no longer exists anywhere: the diff includes files OTHER changes
# merged, so the gate can BLOCK on findings that are not this diff's — or
# accept, as "already at the baseline", a finding this diff introduces. Both
# happened.
#
# NO network here, on purpose. This runs as a `PreToolUse` hook on every
# `git commit`, so a `fetch` would put a remote round-trip — and its timeouts,
# its auth prompts, its outages — in front of every commit in the repo.
# `origin/<base>` is kept fresh by the pre-flight of the reviewer and the
# publisher, which both fetch before they work; in that cycle the ref is
# already current when the hook reads it. Outside it (an offline clone, a repo
# with no remote) the fallback keeps the previous behaviour exactly.
#
# Sets `$base_ref` (the ref actually used, for messages) and `$base_sha` (its
# commit — resolved to a sha because it is BOTH the scan's baseline and part of
# the content cache's fingerprint, so it has to name one immutable commit).
# Returns 1 when neither ref resolves; the caller skips.
navori_resolve_base() {
  local local_sha="" local_short="" origin_short=""
  base_ref="$base"
  base_sha=$(git rev-parse --verify --quiet "origin/$base^{commit}" 2>/dev/null || true)
  if [ -n "$base_sha" ]; then
    base_ref="origin/$base"
    local_sha=$(git rev-parse --verify --quiet "$base^{commit}" 2>/dev/null || true)
    # The lag itself is normal; the lag being SILENT is what cost a day. One
    # line, only when the two refs actually disagree, so "why was that file
    # scanned" has an answer in the transcript instead of a reconstruction.
    if [ -n "$local_sha" ] && [ "$local_sha" != "$base_sha" ]; then
      local_short=$(git rev-parse --short "$local_sha" 2>/dev/null || printf '%s' "$local_sha")
      origin_short=$(git rev-parse --short "$base_sha" 2>/dev/null || printf '%s' "$base_sha")
      echo "ℹ $navori_scan_label: local '$base' ($local_short) ≠ origin/$base ($origin_short) — baseline is origin/$base" >&2
    fi
    return 0
  fi
  base_sha=$(git rev-parse --verify --quiet "$base^{commit}" 2>/dev/null || true)
  [ -n "$base_sha" ] || return 1
  return 0
}

# --- Files in scope (#777) ---------------------------------------------------
# `git diff` for tracked changes PLUS `git ls-files --others` for untracked
# ones.
#
# The untracked half is not an edge case. These hooks are `PreToolUse`: they run
# BEFORE the command they gate. With `git add new.ts && git commit -m x` in ONE
# Bash call — the batching the harness itself recommends in auto mode — the file
# is still untracked when the scan runs, so a list built from `git diff` alone
# reported `0 files to scan` and the gate went green over a file nobody read.
# Agent work is mostly new files, which made that the common case rather than
# the rare one. `--exclude-standard` keeps ignored build output out: generated
# artifacts are not new code.
#
# The two lists are disjoint by construction (`--others` is precisely what the
# index does not track), so there is nothing to de-duplicate.
#
# Both listings carry a sentinel with their exit status: they run inside a
# process substitution, whose status the shell never reports, so a FAILED
# listing (exit 128: unborn HEAD, a corrupt index, a base that vanished
# mid-run) would otherwise be indistinguishable from "nothing changed" — the
# gate printing `0 files to scan` and exiting 0 over a tree it never read
# (#511). The sentinel can never collide with a real record: the pathspec
# restricts both lists to `*.ts`/`*.tsx`.
#
# Sets `$files` (array) and, on failure, `$scan_files_status`. Returns 1 when
# either listing failed, so the caller can report it as "nothing was scanned"
# rather than as a verdict.
navori_collect_scan_files() {
  local sentinel='@navori-scan-status:' f=""
  scan_files_status=""
  files=()
  while IFS= read -r -d '' f; do
    case "$f" in
      "${sentinel}"*)
        scan_files_status="${f#"${sentinel}"}"
        continue
        ;;
    esac
    files+=("$f")
  done < <(
    # `|| rc=$?` and not a bare `$?`: the subshell inherits `set -e`, which
    # would kill it on a failing git call before the sentinel is ever written.
    rc=0
    git diff --name-only -z --diff-filter=ACMRT "$base_sha" -- '*.ts' '*.tsx' || rc=$?
    if [ "$rc" -eq 0 ]; then
      git ls-files --others --exclude-standard -z -- '*.ts' '*.tsx' || rc=$?
    fi
    printf '%s%s\0' "$sentinel" "$rc"
  )
  [ "$scan_files_status" = "0" ] || return 1
  return 0
}

# No command extracted (empty $cmd) → run unconditionally. A real command that
# is NOT a git commit → skip. Anything else → fall through and scan.
if [ -n "$cmd" ] && ! is_scan_trigger "$cmd"; then
  navori_jscpd_reason="jscpd: skipped non-trigger command; no scan"
  exit 0
fi

# A commit that provably lands in ANOTHER repository (#1095) has nothing of its
# diff in this tree; ambiguous shapes keep scanning (fail closed, #454).
if [ -n "$cmd" ]; then
  navori_commit_landing "$cmd"
  if [ "$navori_landing" = foreign ]; then
    navori_jscpd_reason="jscpd: skipped, commit lands in another repository; no scan"
    echo "⊘ jscpd: the commit lands in another repository ($navori_landing_root), not the one this session is anchored in — this repository's scan does not apply; skip" >&2
    exit 0
  fi
fi

# Resolve jscpd: prefer the repo-pinned binary (node_modules/.bin) over a global
# one. A global jscpd can be a DIFFERENT major (e.g. 4.x vs the repo's 5.x) whose
# tokenizer reports different duplication than `pnpm run dup`, so the commit gate
# would measure something other than what the repo declares. Local-first fixes it.
# Availability is settled BEFORE the tree is resolved: a missing tool is the
# cheapest reason to stop, and it must not be masked by a tree that fails to
# resolve.
JSCPD_BIN=""
hook_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -n "$hook_root" ] && [ -x "$hook_root/node_modules/.bin/jscpd" ]; then
  JSCPD_BIN="$hook_root/node_modules/.bin/jscpd"
elif command -v jscpd >/dev/null 2>&1; then
  JSCPD_BIN="jscpd"
fi
if [ -z "$JSCPD_BIN" ]; then
  navori_jscpd_reason="jscpd: skipped, scanner unavailable; no scan"
  echo "⊘ jscpd not available (neither pinned in the repo nor installed globally) — skip (install: pnpm add -D jscpd)" >&2
  exit 0
fi

# Run from the tree the commit acts on — NOT from the hook process's cwd, which
# is the main repo even when the diff lives in an agent worktree (#454). Also
# keeps changed paths relative, so a repo path with spaces stays robust; the
# NUL-delimited read handles spaces in filenames, and the
# `-- '*.ts' '*.tsx'` pathspec filters by extension without a pipe.
tree=$(navori_worktree)
if [ -z "$tree" ]; then
  navori_jscpd_reason="jscpd: skipped, working tree unresolved; no scan"
  echo "⊘ jscpd: no git working tree resolved for this command — skip" >&2
  exit 0
fi
cd "$tree"

# Now that the tree is known, its OWN pinned binary wins: same rationale as
# above — measure what the scanned repo declares, not what the repo the hook
# process happens to sit in does.
if [ -x "$tree/node_modules/.bin/jscpd" ]; then
  JSCPD_BIN="$tree/node_modules/.bin/jscpd"
fi

# branchBase is shell-quoted at render time via the shq: marker (#197/#249):
# hostile values in navori.config.json land here as inert literals, never
# executable (this hook runs on every git commit via PreToolUse(Bash)).
base='develop'

if ! navori_resolve_base; then
  navori_jscpd_reason="jscpd: skipped, baseline unresolved; no scan"
  echo "⊘ neither 'origin/$base' nor '$base' exists in $tree — skip jscpd" >&2
  exit 0
fi

if ! navori_collect_scan_files; then
  navori_jscpd_reason="jscpd: changed-file listing failed; scan not validated"
  echo "✗ jscpd: listing the changed files FAILED (exit ${scan_files_status:-unknown}) in $tree — NOTHING was scanned" >&2
  echo "  this is not a duplication verdict: no file was compared against $base_ref" >&2
  exit 1
fi

# An empty scan is NOT a silent green (#454): say which tree and which base
# produced it, so "there was nothing to scan" reads differently from "I scanned
# and found nothing".
if [ ${#files[@]} -eq 0 ]; then
  navori_jscpd_reason="jscpd: skipped, zero changed TS/TSX files; no scan"
  echo "⊘ jscpd: 0 files to scan — no *.ts/*.tsx differ from $base_ref in $tree" >&2
  exit 0
fi

echo "▶ jscpd: ${#files[@]} changed file(s) vs $base_ref in $tree" >&2

# Capability probe (only reached when there are files to scan): jscpd added
# `--baseline-from-ref`/`--fail-on-new-clones` in 5.1.1. A binary older than
# that silently ignores or rejects the flags this hook depends on, and its
# own `--version` self-report is not reliable enough to gate on (5.1.0
# prints `cpd 5.0.16`) — so the question is asked directly, of the actual
# binary, via `--help`.
#
# Captured to a variable and matched with `case`, never piped into `grep -q`:
# under `set -o pipefail` a `grep -q` that finds its match early closes the
# pipe, jscpd gets SIGPIPE, and the probe would misread a supported binary as
# unsupported.
navori_jscpd_help=$("$JSCPD_BIN" --help 2>&1 || true)
navori_jscpd_has_baseline=0
navori_jscpd_has_new_clones=0
case "$navori_jscpd_help" in
  *--baseline-from-ref*) navori_jscpd_has_baseline=1 ;;
esac
case "$navori_jscpd_help" in
  *--fail-on-new-clones*) navori_jscpd_has_new_clones=1 ;;
esac
if [ "$navori_jscpd_has_baseline" -ne 1 ] || [ "$navori_jscpd_has_new_clones" -ne 1 ]; then
  navori_jscpd_reason="jscpd: blocked, required flags unavailable; not a duplication verdict"
  echo "✗ jscpd: $JSCPD_BIN lacks --baseline-from-ref/--fail-on-new-clones (needs jscpd >= 5.1.1) — upgrade it (global: pnpm add -g jscpd@^5.1.1 · repo-pinned: pnpm add -D jscpd@^5.1.1) — BLOCKED, this is not a duplication verdict" >&2
  exit 2
fi

tmpdir=$(mktemp -d)
# COMPOSED, not replaced: bash keeps exactly ONE EXIT trap, so a bare
# `trap 'rm -rf ...' EXIT` here silently discards the audit recorder installed
# above — and it does so precisely on the path where this hook does real work,
# which is the one worth recording. The cleanup runs first so the temp dir goes
# away even if the recorder were ever to hang.
trap 'navori_jscpd_exit=$?; rm -rf "$tmpdir" 2>/dev/null || true; navori_audit_on_exit "$navori_jscpd_exit"' EXIT

# The host can kill this process at its hook timeout, before any trap records a
# verdict. Persist a start marker first; audit correlates it with the terminal
# record by tool_use_id and reports an unfinished gate. #797 brought it here
# from `quality-gate-pre-commit`, the only gate that had one: for the other two
# a SIGKILL was undetectable, so the detector covered one gate of three.
navori_audit_log "gate-started" "inicio del escaneo de jscpd" || true

# `>&2` is not cosmetic (#510): a PreToolUse hook shows the user its stderr and
# swallows its stdout, so the console reporter's clone table — the whole point
# of the gate — used to be written where nobody could read it.
scan_status=0
"$JSCPD_BIN" \
  --min-tokens 100 \
  --min-lines 10 \
  --mode strict \
  --baseline-from-ref "$base_sha" \
  --fail-on-new-clones 0 \
  --reporters console \
  --output "$tmpdir" \
  -- "${files[@]}" >&2 || scan_status=$?

# PreToolUse EXIT CONTRACT (#510). Claude Code blocks a tool call ONLY on exit
# 2; every other non-zero code is shown to the user and the call PROCEEDS. This
# script used to END on the `jscpd` invocation, so `set -e` handed jscpd's own
# code straight through — and jscpd maps "new clones" to 1. The gate printed a
# progress line and blocked exactly nothing.
#
# The explicit `0` after `--fail-on-new-clones` and the `--` before the paths
# are both load-bearing: the flag is `[<N>]`-greedy and swallows the first path
# as its own value when either is missing, turning it into a jscpd usage error
# (exit 2, read below as "not a verdict") — the gate would then silently stop
# blocking new clones instead of announcing it.
#
# TODO(fidelity): jscpd spends exit 1 on BOTH "new clones" and an internal
# crash, so the outcome blocks conservatively but is NOT a confirmed clone
# finding. Split the mapping if jscpd ever gives these distinct codes, or if
# ambiguous failures become frequent enough to erode trust in the gate.
if [ "$scan_status" -eq 0 ]; then
  navori_jscpd_reason="jscpd: clean scan, no new clones"
  echo "✓ jscpd: ${#files[@]} file(s) scanned — no new clones vs $base_ref" >&2
  exit 0
fi
if [ "$scan_status" -eq 1 ]; then
  navori_jscpd_reason="jscpd: blocked ambiguous scanner exit 1 (new clones or internal failure); not confirmed clones"
  echo "✗ jscpd: ambiguous exit 1 (new clones or internal failure) vs $base_ref — BLOCKED; not a confirmed duplication verdict" >&2
  exit 2
fi
echo "✗ jscpd: the run FAILED with exit $scan_status (not a duplication verdict) — nothing was validated" >&2
navori_jscpd_reason="jscpd: scanner failed with exit $scan_status; scan not validated"
exit 1
# navori:managed end id="jscpd-script-check-jscpd"
